# Lesson 2

Please follow the exercises below (exercises are within the python comments)

## Pandas

In [2]:
# import  the 'panda' module as the alias 'pd'
import pandas as pd

# Read the CSV file 'kidney_function.csv' into a DataFrame called 'df'
df = pd.read_csv('kidney_function.csv')

# Print the DataFrame
print(df)

    Patient_ID        Date  GFR (mL/min)  Creatinine (mg/dL)  Urea (mg/dL)  \
0            1  2022-01-01            60                 1.1            30   
1            1  2022-02-01            58                 1.2            32   
2            1  2022-03-01            55                 1.3            34   
3            1  2022-04-01            52                 1.4            36   
4            1  2022-05-01            50                 1.4            38   
5            1  2022-06-01            45                 1.5            40   
6            1  2022-07-01            40                 1.6            45   
7            1  2022-08-01            35                 1.7            48   
8            1  2022-09-01            32                 1.9            50   
9            1  2022-10-01            30                 2.0            55   
10           1  2022-11-01            28                 2.1            58   
11           1  2022-12-01            26                 2.2    

In [3]:
# Update the 'Stage' field for the entry with 'Date' '2022-12-01' to 5
df.loc[df['Date'] == '2022-12-01', 'Stage'] = 5

# Print the updated DataFrame to verify the change
print(df)

    Patient_ID        Date  GFR (mL/min)  Creatinine (mg/dL)  Urea (mg/dL)  \
0            1  2022-01-01            60                 1.1            30   
1            1  2022-02-01            58                 1.2            32   
2            1  2022-03-01            55                 1.3            34   
3            1  2022-04-01            52                 1.4            36   
4            1  2022-05-01            50                 1.4            38   
5            1  2022-06-01            45                 1.5            40   
6            1  2022-07-01            40                 1.6            45   
7            1  2022-08-01            35                 1.7            48   
8            1  2022-09-01            32                 1.9            50   
9            1  2022-10-01            30                 2.0            55   
10           1  2022-11-01            28                 2.1            58   
11           1  2022-12-01            26                 2.2    

In [4]:
# Load data from the 'patient_data.csv' into a few DataFrame called 'df_2'
df_2 = pd.read_csv('patient_data.csv')

# Print the df_2 DataFrame
print(df_2)

   Patient_ID     Name  Age  Gender      Diagnosis Blood Pressure  \
0           1    Alice   45  Female   Hypertension         140/90   
1           2      Bob   55    Male       Diabetes         130/85   
2           3  Charlie   65    Male   Hypertension         150/95   
3           4    David   70    Male  Heart Disease        160/100   
4           5      Eva   50  Female   Hypertension         135/88   
5           5     John   55    Male   Hypertension         137/98   

   Cholesterol  Glucose Level    Outcome  
0          200             90  Recovered  
1          180            150   Unstable  
2          220            100     Stable  
3          240            110  Recovered  
4          210             95   Unstable  
5          200             98   Unstable  


In [5]:
# Filter the df_2 DataFrame for all ages over 55
df_2_over_55 = df_2[df_2['Age'] > 55]

# Print the filtered DataFrame
print(df_2_over_55)

   Patient_ID     Name  Age Gender      Diagnosis Blood Pressure  Cholesterol  \
2           3  Charlie   65   Male   Hypertension         150/95          220   
3           4    David   70   Male  Heart Disease        160/100          240   

   Glucose Level    Outcome  
2            100     Stable  
3            110  Recovered  


In [6]:
# Print out some basic statistics about the df_2 DataFrame using the 'describe()' method.
print(df_2.describe())

       Patient_ID        Age  Cholesterol  Glucose Level
count    6.000000   6.000000     6.000000       6.000000
mean     3.333333  56.666667   208.333333     107.166667
std      1.632993   9.309493    20.412415      22.003788
min      1.000000  45.000000   180.000000      90.000000
25%      2.250000  51.250000   200.000000      95.750000
50%      3.500000  55.000000   205.000000      99.000000
75%      4.750000  62.500000   217.500000     107.500000
max      5.000000  70.000000   240.000000     150.000000


## Numpy

In [7]:
# import the 'numpy' module as the alias 'np'
import numpy as np

# Create a 1x7 array with random numbers. Call the array 'array_1x7'
array_1x7 = np.array([1, 2, 2, 4, 1, 1, 7])

# Print the contents of the above array
print(array_1x7)

[1 2 2 4 1 1 7]


In [8]:
# Print the shape of the array_1x7 array
print(array_1x7.shape)

(7,)


In [9]:
# Update the second element of the array_1x7 array to 3. Remember that indexing starts at 0.
array_1x7[1] = 3

# Print the updated array
print(array_1x7)

[1 3 2 4 1 1 7]


In [10]:
# Creating a 2x7 array with random numbers. Call the array 'array_2x7'
array_2x7 = np.array([[1, 2, 3, 4, 5, 6, 7],
                      [8, 9, 10, 11, 12, 13, 14]])

# Print the contents of the array
print(array_2x7)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Print the shape of the array 'array_2x7'
print(array_2x7.shape)

(2, 7)


In [12]:
# Update the element in the last row and column of the 'array_2x7' array to 0.
array_2x7[1, 6] = 0

# Print the updated array
print(array_2x7)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13  0]]


In [13]:
# Creating a 2x2x7 3D array with random numbers. Call the array 'array_3D'.
array_3D = np.array([[[1, 2, 3, 4, 5, 6, 7],
                      [8, 9, 10, 11, 12, 13, 14]],
                     [[15, 16, 17, 18, 19, 20, 21],
                      [22, 23, 24, 25, 26, 27, 28]]])

# Print the contents of the array
print(array_3D)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]]


In [14]:
# Print the shape of the 3D array
array_3D.shape

(2, 2, 7)

In [15]:
# Update the element in the first row, second column, and first depth of the 'array_3D' array to 1111.
array_3D[0, 1, 0] = 1111

# Print the updated array
print(array_3D)

[[[   1    2    3    4    5    6    7]
  [1111    9   10   11   12   13   14]]

 [[  15   16   17   18   19   20   21]
  [  22   23   24   25   26   27   28]]]


## Scipy

In [16]:
# Import scipy's 'stats' module
from scipy import stats

# You will be working again on the 'df_2' DataFrame. Print the DataFrame to remind yourself of the data.
print(df_2)

   Patient_ID     Name  Age  Gender      Diagnosis Blood Pressure  \
0           1    Alice   45  Female   Hypertension         140/90   
1           2      Bob   55    Male       Diabetes         130/85   
2           3  Charlie   65    Male   Hypertension         150/95   
3           4    David   70    Male  Heart Disease        160/100   
4           5      Eva   50  Female   Hypertension         135/88   
5           5     John   55    Male   Hypertension         137/98   

   Cholesterol  Glucose Level    Outcome  
0          200             90  Recovered  
1          180            150   Unstable  
2          220            100     Stable  
3          240            110  Recovered  
4          210             95   Unstable  
5          200             98   Unstable  


In [17]:
# Split the data into two groups: hypertension and non_hypertension
# Create two new dataframes called 'hypertension' and 'non_hypertension', 
# containing only cholesterol data.
hypertension = df_2[df_2['Diagnosis'] == 'Hypertension']['Cholesterol']

non_hypertension = df_2[df_2['Diagnosis'] != 'Hypertension']['Cholesterol']

# Print the hypertension group
print(f"Hypertension group:\n{hypertension}\n")

# Print the non-hypertension group
print(f"Non-hypertension group:\n{non_hypertension}")

Hypertension group:
0    200
2    220
4    210
5    200
Name: Cholesterol, dtype: int64

Non-hypertension group:
1    180
3    240
Name: Cholesterol, dtype: int64


In [18]:
# Perform a t-test to compare the cholesterol levels between the hypertension and non-hypertension groups
t_score, p_value = stats.ttest_ind(hypertension, non_hypertension)

# Print the t-score
print(f"t-score: {round(t_score, 3)}")

# Print the p-value
print(f"p-value: {round(p_value, 3)}")

t-score: -0.127
p-value: 0.905


In [19]:
# Are these two groups significantly different? Print your answer with an explanation.
print("These values are not significantly different.")
print("This is because the t-score is less than 1 and the p-value is greater than 0.05.")

These values are not significantly different.
This is because the t-score is less than 1 and the p-value is greater than 0.05.
